name: myrefectly
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_custom_clippers: ^2.1.0
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  getwidget: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.69.0
  syncfusion_flutter_charts: ^27.1.56
  flare_flutter: ^3.0.2
  rive: ^0.13.4
  flutter_slidable: ^3.1.1
  rect_getter: ^1.1.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  syncfusion_flutter_gauges: ^27.1.56
  flutter_shaders: ^0.1.2
  local_auth: ^2.3.0
  hive: ^2.2.3
  flutter_toggle_tab: ^1.4.1
  path_provider: ^2.1.0
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  hive_generator: ^2.0.1
  implicitly_animated_reorderable_list: ^0.4.2
  speech_to_text: ^7.0.0
  json_annotation: ^4.8.0
  flutter_secure_storage: ^9.2.2
  rtf_textfield: ^1.0.1
  workmanager: ^0.5.2
  connectivity_plus: ^6.0.5
  http: any
  uuid: ^4.5.1
  flutter_image_compress: ^2.3.0
  path: any
  calendar_date_picker2: ^1.1.7
  flutter_local_notifications: ^17.2.4
  permission_handler: ^11.3.1
  # awesome_notifications: ^0.10.0
  #   # Awesome plugins for local notifications
  # awesome_notifications_core: ^0.10.0 # use the latest core version available
  # # Awesome plugins for remote push notifications
  # awesome_notifications_fcm: ^0.10.0 # This version is managed by core plugin
  timezone: any
  image_gallery_saver: ^2.0.3
  image_watermark: ^0.1.0
  lite_rolling_switch: ^1.0.1
  flutter_multi_slider: ^2.0.1
  intl: any
  livespeechtotext: ^1.0.9
  image: any
  dio: ^5.7.0
  restart_app: ^1.3.2
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.12
  json_serializable: ^6.7.0
  test: ^1.25.7
  mockito: ^5.4.4
  rename: ^2.0.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/ico/app_icon_reflectly.png"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/static/Quicksand-Medium.ttf
        - asset: assets/fonts/static/Quicksand-Bold.ttf
        - asset: assets/fonts/static/Quicksand-Light.ttf
          weight: 700
    - family: Second
      fonts:
        #- asset: assets/fonts/TT-Norms-Pro-ExtraBold.ttf
        - asset: assets/fonts/TT-Norms-Pro-Medium.ttf
        - asset: assets/fonts/TT-Norms-Pro-Regular.ttf
        - asset: assets/fonts/TT-Norms-Pro-DemiBold.ttf
          weight: 700
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/mood/
    - assets/ico/
    - assets/flare/
    - assets/completion_topic_avatars/
    - assets/challenge_images/
    - assets/quote_backgrounds/
    - assets/timeline_avatars/
    - assets/navigator_icon/
    - assets/quote_backgrounds/thumbnails/
    - assets/quote_categories/thumbnails/
    - assets/activities/
    - assets/feelings/
    - assets/all/
    - assets/fonts/IMGF/
  # shaders:
  #   - shaders/ink_sparkle.frag
  #   - shaders/shadow.frag 
  #   - shaders/sampler.frag 
  #   - shaders/solid_color.frag 
  # shaders:
  #   # - shaders/ink_sparkle.frag
  #   - assets/shaders/ink_sparkle.frag
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
