import 'package:injectable/injectable.dart';

import 'package:myrefectly/core/network/dio_client.dart';
import 'package:myrefectly/features/auth/data/datasource/auth_remote_datasource.dart';

/// Registers generated / 3rd-party auth classes.
///
/// [AuthRemoteDataSource] is generated by Retrofit, so we can't
/// annotate it directly — register it here instead.
@module
abstract class AuthModule {
  @lazySingleton
  AuthRemoteDataSource authDataSource(DioClient dioClient) =>
      AuthRemoteDataSource(dioClient.dio);
}
