// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApZ9UBOMTVDIHbbZ-gwO5Wn9p3LatLDZs',
    appId: '1:1082619284736:web:0ed3c45b178cf8929777e5',
    messagingSenderId: '1082619284736',
    projectId: 'reflectly-90908',
    authDomain: 'reflectly-90908.firebaseapp.com',
    storageBucket: 'reflectly-90908.appspot.com',
    measurementId: 'G-1YVWLY2TR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFSY-aelqj9xSFLL9eaVw9rcza2iMTz7c',
    appId: '1:1082619284736:android:d155b043001c4e529777e5',
    messagingSenderId: '1082619284736',
    projectId: 'reflectly-90908',
    storageBucket: 'reflectly-90908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ1yjhkci5GK0erDN9W-Kcf-T24soixoM',
    appId: '1:1082619284736:ios:22be9cb1a692ba079777e5',
    messagingSenderId: '1082619284736',
    projectId: 'reflectly-90908',
    storageBucket: 'reflectly-90908.appspot.com',
    iosBundleId: 'com.example.myrefectly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ1yjhkci5GK0erDN9W-Kcf-T24soixoM',
    appId: '1:1082619284736:ios:22be9cb1a692ba079777e5',
    messagingSenderId: '1082619284736',
    projectId: 'reflectly-90908',
    storageBucket: 'reflectly-90908.appspot.com',
    iosBundleId: 'com.example.myrefectly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApZ9UBOMTVDIHbbZ-gwO5Wn9p3LatLDZs',
    appId: '1:1082619284736:web:a05690e93e99546b9777e5',
    messagingSenderId: '1082619284736',
    projectId: 'reflectly-90908',
    authDomain: 'reflectly-90908.firebaseapp.com',
    storageBucket: 'reflectly-90908.appspot.com',
    measurementId: 'G-Q886FGZC8Q',
  );

}